[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@diamond/=src/',
    '@diamond-script/=script/',
    '@diamond-test/=test/',
]
auto_detect_remappings = true
ffi = true
optimizer_runs = 100_000
evm_version = "prague"
allow_internal_expect_revert = false
names = true
sizes = true
